server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: jsonplaceholder
          uri: https://jsonplaceholder.typicode.com
          predicates:
            - Path=/json/todos/**
          filters:
            - RewritePath=/json,/

        - id: gorest
          uri: https://gorest.co.in
          predicates:
            - Path=/gorest/public-api/users/**
          filters:
            - RewritePath=/gorest,/

        - id: httpbin
          uri: https://httpbin.org
          predicates:
            - Path=/httpbin/get/**
          filters:
            - RewritePath=/httpbin,/
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET